Fixes issue #1 : Added  Material slider to adjust the brush size
iiitl/undraw pull request #11
Opened 2022-10-07 12:09 UTC by Smarshal21

Added  Material slider to adjust the brush size
![Screenshot_1665141792](https://user-images.githubusercontent.com/99678760/194550011-f921760d-768b-4a83-ad80-a978ec37e21c.png)
![Screenshot_1665141835](https://user-images.githubusercontent.com/99678760/194550019-69ec45c1-77d2-45b8-b66e-94baacecc5a6.png)

https://user-images.githubusercontent.com/99678760/194550057-682bad55-c407-4e56-ab20-294204266e2f.mp4

2022-10-08 09:23 UTC, Smarshal21 commented
@rishidyno can you please review this PR

2022-10-09 13:09 UTC, rishidyno requested changes

2022-10-09 13:09 UTC, rishidyno commented on app/src/main/res/layout/dialog_brush_size.xml
>  </layout>
Add EOL

2022-10-09 13:09 UTC, rishidyno commented on app/src/main/res/layout/dialog_brush_size.xml
> +            android:id="@+id/slidermo"
Rename it to `brush_size_slider`

2022-10-09 14:16 UTC, Smarshal21 commented
@rishidyno added the requested changes

2022-10-19 08:48 UTC, rishidyno commented
LGTM

2022-10-19 08:48 UTC, merged