Fixes issue #3 : (added save feature)
iiitl/undraw pull request #6
Opened 2022-10-05 11:48 UTC by RockingRishav

![Screenshot_20221003-180207_undraw](https://user-images.githubusercontent.com/96726333/194053293-4ae4176d-bebb-4142-b5cc-70ee4985f645.jpg)

2022-10-05 11:51 UTC, RockingRishav commented
@rishidyno sir, could you please review my PR and give suggestion if required otherwise merge it with hacktoberfest-accepted label.

2022-10-06 10:24 UTC, rishidyno requested changes
Add a screenshot showing the saved images in the device storage.

2022-10-06 10:24 UTC, rishidyno commented on app/src/main/AndroidManifest.xml
>  </manifest>
EOL is missing here

2022-10-06 10:24 UTC, rishidyno commented on app/src/main/java/com/rihsi/dyno/undraw/MainActivity.kt
remove extra line

2022-10-06 10:24 UTC, rishidyno commented on app/src/main/res/xml/path.xml
> +</paths>
Add EOL

2022-10-06 10:27 UTC, rishidyno commented
Please also delete 2 generated files.

2022-10-06 10:29 UTC, RockingRishav commented on app/src/main/AndroidManifest.xml
>  </manifest>
sir what does EOL stands for?

2022-10-06 10:33 UTC, rishidyno commented
@RockingRishav I have updated the wiki PTAL look there and do the required changes.

2022-10-06 11:42 UTC, RockingRishav commented
@rishidyno sir, i have applied the changes please recheck once

2022-10-06 14:15 UTC, rishidyno commented
> @rishidyno sir, i have applied the changes please recheck once

I want you to locate it in phone.

2022-10-06 17:23 UTC, RockingRishav commented
@rishidyno sir, Finally implemented the save to gallery feature please review it.

2022-10-07 05:36 UTC, merged

2022-10-07 06:09 UTC, rishidyno commented
LGTM and Merged.