Fixed issue #4 : (share feature)
iiitl/undraw pull request #9
Opened 2022-10-07 05:45 UTC by RockingRishav

![Screenshot_20221007-111259_Android System](https://user-images.githubusercontent.com/96726333/194476060-fb211cc1-3b98-495a-a61c-46f910bbb9fd.jpg)

2022-10-07 05:52 UTC, RockingRishav commented
@rishidyno sir, can you review this PR and give suggestions if required otherwise merge

2022-10-07 06:05 UTC, rishidyno requested changes
nit-changes needed

2022-10-07 06:05 UTC, rishidyno commented on app/src/main/java/com/rihsi/dyno/undraw/MainActivity.kt
> +            checkforshare=0
Make this variable camel case.

2022-10-07 06:07 UTC, rishidyno commented
@RockingRishav Just add a video of you sharing this on one platform of your choice, like WhatsApp.

2022-10-07 06:32 UTC, RockingRishav commented
Video added to comment

2022-10-09 13:46 UTC, merged

2022-10-09 13:53 UTC, rishidyno commented
@RockingRishav Always link the issue for which you are creating the PR. 
`LIKE - Fix #4`
on first comment.
![image](https://user-images.githubusercontent.com/78549195/194760687-46b9664c-22c4-42f1-a807-e7bcd2929224.png)
Like I have done in this PR.